version: 2
jobs:
  build:
    docker:
      - image: ubuntu:bionic

    environment:
      DOCKER_CE_VER: 18.03.1
      DOCKER_COMPOSE_VER: 1.21.2

    steps:
      - checkout

      # Install some packages
      - run:
          name: Install packages
          command: |
            apt-get update
            apt-get install -y curl

      # Install docker client
      #   ref. https://docs.docker.com/install/linux/docker-ce/ubuntu/
      - run:
          name: Install Docker client
          command: |
            set -x
            curl -L -o /tmp/docker-${DOCKER_CE_VER}.tgz https://download.docker.com/linux/ubuntu/dists/bionic/pool/stable/amd64/docker-ce_${DOCKER_CE_VER}~ce~3-0~ubuntu_amd64.deb
            dpkg -i /tmp/docker-${DOCKER_CE_VER}.tgz

      # Install docker-compose
      #   ref. https://docs.docker.com/compose/install/
      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VER}/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose

      # It is needed to activate the remote docker environment
      #   see. https://circleci.com/docs/2.0/docker-compose/
      - setup_remote_docker

      # Build and run integration test
      - run:
          name: Run integration tests
          command: |
            test/e2e.sh
