version: 2
jobs:
  build:
    docker:
      - image: debian:jessie

    environment:
      DOCKER_VER: 17.03.0-ce
      DOCKER_COMPOSE_VER: 1.11.2

    steps:
      - checkout

      # Install some packages
      - run:
          name: Install packages
          command: |
            apt-get update
            apt-get install -y curl

      # Install docker client
      #   ref. https://github.com/CircleCI-Public/circleci-demo-docker/blob/docker-compose/.circleci/config.yml
      - run:
          name: Install Docker client
          command: |
            set -x
            curl -L -o /tmp/docker-${DOCKER_VER}.tgz https://get.docker.com/builds/Linux/x86_64/docker-${DOCKER_VER}.tgz
            tar -xz -C /tmp -f /tmp/docker-${DOCKER_VER}.tgz
            mv /tmp/docker/* /usr/bin

      # Install docker-compose
      #   ref. https://github.com/CircleCI-Public/circleci-demo-docker/blob/docker-compose/.circleci/config.yml
      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VER}/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose

      # It is needed to activate the remote docker environment
      #   see. https://circleci.com/docs/2.0/docker-compose/
      - setup_remote_docker

      # Build and run integration test
      - run:
          name: Run integration tests
          command: |
            test/e2e.sh
